Fix undefined variable when accessing active support encryptor fallback (#31)
Related to: #29 

creating new credentials fails with 

```
0.4.0/lib/diffcrypt/rails/encrypted_configuration.rb:102:in `decrypt': undefined method `decrypt_and_verify' for nil:NilClass (NoMethodError)
```

it seems `decrypt_and_verify` is never called, thus `@decrypt_and_verify` is not populated and hence results in this error.

Not sure if
```ruby
      def active_support_encryptor
        @active_support_encryptor = ActiveSupport::MessageEncryptor.new(
          [key].pack('H*'),
          cipher: @diffcrypt_file.cipher,
        )
      end
```

was intended to memorize the AS Message Encryptor instance, if so, we can drop in `@active_support_encryptor ||= ...`.